[package]
name = "vorarbeiter"
description = "A small process supervisor that shutdowns child processes"
version = "0.1.0"
authors = ["Marc Brinkmann <git@marcbrinkmann.de>"]
edition = "2018"
license = "MIT OR Apache-2.0"


[dependencies]
nix = "0.19.1"
